In [3]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\cl501_26\Downloads\phiusiil+phishing+url+dataset\PhiUSIIL_Phishing_URL_Dataset.csv")
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

### Conversion of categorical(encoded as numeric) columns to category dtype

In [23]:
# Display whether the column is categorical or numerical
def identify_column_type(column):
    dtype = df[column].dtype
    unique_values = df[column].nunique()
    num_values = len(df[column])
    
    # Criteria for categorical data encoded as numbers
    if pd.api.types.is_numeric_dtype(dtype):
        if unique_values < 10:  # Example threshold for potential categorical
            # Further check for categorical patterns
            return 'Categorical (Encoded as Numeric)'
        else:
            return 'Numerical'
    elif pd.api.types.is_string_dtype(dtype) or pd.api.types.is_categorical_dtype(dtype):
        return 'Categorical'
    else:
        return 'Other'

# Determine column types
print("Column Name, Data Type, Type Category:")
for column in df.columns:
    column_type = identify_column_type(column)
    if column_type=='Categorical (Encoded as Numeric)':
        df[column]=df[column].astype('category')
    print(f"Column Name: {column}, Data Type: {df[column].dtype}, Type Category: {column_type}")

Column Name, Data Type, Type Category:
Column Name: FILENAME, Data Type: object, Type Category: Categorical
Column Name: URL, Data Type: object, Type Category: Categorical
Column Name: URLLength, Data Type: int64, Type Category: Numerical
Column Name: Domain, Data Type: object, Type Category: Categorical
Column Name: DomainLength, Data Type: int64, Type Category: Numerical
Column Name: IsDomainIP, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: TLD, Data Type: object, Type Category: Categorical
Column Name: URLSimilarityIndex, Data Type: float64, Type Category: Numerical
Column Name: CharContinuationRate, Data Type: float64, Type Category: Numerical
Column Name: TLDLegitimateProb, Data Type: float64, Type Category: Numerical
Column Name: URLCharProb, Data Type: float64, Type Category: Numerical
Column Name: TLDLength, Data Type: int64, Type Category: Numerical
Column Name: NoOfSubDomain, Data Type: int64, Type Category: Numerical
Column Name: HasObfuscation, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfObfuscatedChar, Data Type: int64, Type Category: Numerical
Column Name: ObfuscationRatio, Data Type: float64, Type Category: Numerical
Column Name: NoOfLettersInURL, Data Type: int64, Type Category: Numerical
Column Name: LetterRatioInURL, Data Type: float64, Type Category: Numerical
Column Name: NoOfDegitsInURL, Data Type: int64, Type Category: Numerical
Column Name: DegitRatioInURL, Data Type: float64, Type Category: Numerical
Column Name: NoOfEqualsInURL, Data Type: int64, Type Category: Numerical
Column Name: NoOfQMarkInURL, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfAmpersandInURL, Data Type: int64, Type Category: Numerical
Column Name: NoOfOtherSpecialCharsInURL, Data Type: int64, Type Category: Numerical
Column Name: SpacialCharRatioInURL, Data Type: float64, Type Category: Numerical
Column Name: IsHTTPS, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: LineOfCode, Data Type: int64, Type Category: Numerical
Column Name: LargestLineLength, Data Type: int64, Type Category: Numerical
Column Name: HasTitle, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: Title, Data Type: object, Type Category: Categorical
Column Name: DomainTitleMatchScore, Data Type: float64, Type Category: Numerical
Column Name: URLTitleMatchScore, Data Type: float64, Type Category: Numerical
Column Name: HasFavicon, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: Robots, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: IsResponsive, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfURLRedirect, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfSelfRedirect, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasDescription, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfPopup, Data Type: int64, Type Category: Numerical
Column Name: NoOfiFrame, Data Type: int64, Type Category: Numerical
Column Name: HasExternalFormSubmit, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasSocialNet, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasSubmitButton, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasHiddenFields, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasPasswordField, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: Bank, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: Pay, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: Crypto, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: HasCopyrightInfo, Data Type: category, Type Category: Categorical (Encoded as Numeric)
Column Name: NoOfImage, Data Type: int64, Type Category: Numerical
Column Name: NoOfCSS, Data Type: int64, Type Category: Numerical
Column Name: NoOfJS, Data Type: int64, Type Category: Numerical
Column Name: NoOfSelfRef, Data Type: int64, Type Category: Numerical
Column Name: NoOfEmptyRef, Data Type: int64, Type Category: Numerical
Column Name: NoOfExternalRef, Data Type: int64, Type Category: Numerical
Column Name: label, Data Type: category, Type Category: Categorical (Encoded as Numeric)

In [24]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

### Removing unneccessary columns

In [25]:
df.drop(["FILENAME","URL","Domain"], axis=1, inplace=True)

In [26]:
df.head()

,URLLength,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,31,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,...,0,0,1,34,20,28,119,0,124,1
1,23,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,...,0,0,1,50,9,8,39,0,217,1
2,29,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,...,0,0,1,10,2,7,42,2,5,1
3,26,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,...,1,1,1,3,27,15,22,1,31,1
4,33,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,...,1,0,1,244,15,34,72,1,85,1

In [29]:
df.select_dtypes("object")

        TLD                                              Title
0       com  à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...
1        de              johannes gutenberg-universitÃ¤t mainz
2        uk                               voice fm southampton
3       com  home page: seminars in fetal and neonatal medi...
4       org                     fundaciÃ³n rewilding argentina
...     ...                                                ...
235790  com                                     skincareliving
235791   uk                                      winchestergov
235792   be                                   nononsensedesign
235793  dev          patient-cell-40f5updatedlogmyloginworkers
235794  com                                 alternativefinland

[235795 rows x 2 columns]

In [39]:
a = df.groupby("TLD")["label"].count().nlargest(50)
a

TLD
com     112554
org      18793
net       7097
app       6508
uk        6395
co        5422
io        4201
de        3996
ru        3875
au        2979
dev       2345
top       2329
jp        2219
it        1887
edu       1861
fr        1858
br        1846
nl        1727
ca        1614
info      1566
site      1482
xyz       1473
link      1463
in        1379
pl        1339
gov       1276
cf        1203
ga        1111
us        1108
me        1006
ml         995
cn         993
eu         980
id         802
es         705
se         704
be         696
nz         614
cz         587
ch         560
ro         549
at         517
club       517
za         508
gr         500
mx         498
gq         493
page       490
ie         468
biz        429
Name: label, dtype: int64

In [45]:
b = df.groupby(["TLD","label"])["IsDomainIP"].count().nsmallest(10)
b

C:\Users\cl501_27\AppData\Local\Temp\ipykernel_14628\662164429.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  b = df.groupby(["TLD","label"])["IsDomainIP"].count().nsmallest(10)

TLD  label
100  1        0
101  1        0
103  1        0
106  1        0
107  1        0
108  1        0
11   1        0
110  1        0
111  1        0
116  1        0
Name: IsDomainIP, dtype: int64

In [7]:
df['label'].to_csv('outputlabel.csv')